### ISSUE TITLE
无法高亮除了js、css、html以外的其它语言

### ISSUE THREAD

**Issue by conanliuhuan** [code-farmer-i/vue-markdown-editor#101]
根据文档 《vite 中扩展代码高亮语言包》这一节，已经安装了：vite-plugin-prismjs插件，并且在：vite.config.js 中添加了引入所有语言包的代码（和文档一样）

但除了js、css、html（我只知道这几个）以外，如json、md、shell，都无法高亮。

P.S. 在你的文档页面：https://code-farmer-i.github.io/vue-markdown-editor/zh/theme/vuepress.html#vite-%E4%B8%AD%E6%89%A9%E5%B1%95%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE%E8%AF%AD%E8%A8%80%E5%8C%85
最下面的编辑器中，输入markdown的语法之后，其实也没高亮（看起来你应该是引入了所有语言的）

**Comment by code-farmer-i** [comment]
更新 vite-plugin-prismjs 插件到最新版本即可解决
