### ISSUE TITLE
图片点击后，显示功能消失

### ISSUE THREAD

**Issue by conanliuhuan** [code-farmer-i/vue-markdown-editor#102]
在旧版本中点击图片，会有一个灯箱功能，图片会放大显示。然而重新 npm install之后，就没了

**Comment by code-farmer-i** [comment]
图片预览功能在[2.3.7版本](http://ckang1229.gitee.io/vue-markdown-editor/zh/changelog.html#_1-7-7-2-3-7)已经移除，请通过image-click事件拿到的参数自行实现。
