### ISSUE TITLE
依赖的element-plus升级到1.1.0吧

### ISSUE THREAD

**Issue by wangzl1163** [code-farmer-i/vue-markdown-editor#108]

**Comment by KawaiiZapic** [comment]
There is a breaking change in Element Plus, breaked almost all import that written before this.  
Here is the dicussion about this change: [Element-Plus#3020](https://github.com/element-plus/element-plus/discussions/3020)
  
  
\* P.S
I fork this repo and try to find out which part is incompatible with ElementPlus 1.1.0, but the result is too confusing.   
This repo does not use Element Plus anywhere, but still add Element Plus as a dependency.    
![Only in package.json](https://user-images.githubusercontent.com/45936772/130843232-ea58d0f3-f0b5-4ec0-8799-d01efce955ea.png)

**Comment by code-farmer-i** [comment]
已经移除该依赖项
