### ISSUE TITLE
:grinning: 看起来效果很好，功能建议

### ISSUE THREAD

**Issue by luoyunchong** [code-farmer-i/vue-markdown-editor#11]
:grinning: :grinning::grinning:

您好

同步滚动建议。右侧滚动时，左侧的md没有同步滚动。看起来，左侧滚动后，右侧滚动稍微有些延迟。

**Comment by code-farmer-i** [comment]
滚动的高度要做动态计算，所以同步滚动加了防抖，会在左侧滚动后延迟一定时间做计算后再同步到右侧。
