### ISSUE TITLE
大佬，能增加标题序号吗

### ISSUE THREAD

**Issue by ashuicoder** [code-farmer-i/vue-markdown-editor#112]
类似于这种，要不然看着太痛苦了
![image](https://user-images.githubusercontent.com/47807522/134614886-202b87b3-ef86-4530-8fde-3e6696e5c5a8.png)

**Comment by code-farmer-i** [comment]
这序号自己加上不就行了吗

**Comment by liyangyangi** [comment]
哈哈 标题里自己写上啊
