### ISSUE TITLE
大佬。preview.js的props的top属性能否传值

### ISSUE THREAD

**Issue by lfc625** [code-farmer-i/vue-markdown-editor#116]
![image](https://user-images.githubusercontent.com/13405241/139396655-1dd05530-543c-4093-98e8-3563ecc8f35e.png)

**Comment by code-farmer-i** [comment]
什么场景？

**Comment by lfc625** [comment]
目录导航时候定位在页面最上方被header头挡住

**Comment by code-farmer-i** [comment]
![image](https://user-images.githubusercontent.com/15082905/139614965-0a32aaba-6f3f-4b30-a917-fb33b15bd4ad.png)
这个方法可以传top啊

**Comment by lfc625** [comment]
目录导航可以复写这个方法吗？还是需要自定义一个目录导航？

**Comment by code-farmer-i** [comment]
你在预览区域自定义了一个浮动的header？

**Comment by lfc625** [comment]
是的，有一个fixed的header

**Comment by code-farmer-i** [comment]
你这个header是fixed定位的？

**Comment by lfc625** [comment]
![image](https://user-images.githubusercontent.com/13405241/139791898-1d902321-20b3-4d9c-9cb3-d52af4450253.png)
大佬，预览模式下点击目录导航标题会定位到最上部 hearder是fixed定位的

**Comment by lfc625** [comment]
![image](https://user-images.githubusercontent.com/13405241/139792572-d49ca1fb-d3fc-4ec0-9a52-0cfd26071c89.png)
大佬有什么办法吗？

**Comment by code-farmer-i** [comment]
为啥不自定义锚点啊 http://ckang1229.gitee.io/vue-markdown-editor/zh/senior/anchor.html
