### ISSUE TITLE
HTML tags not rendering correctly

### ISSUE THREAD

**Issue by Qonflux** [code-farmer-i/vue-markdown-editor#123]
Is there any way I can whitelist certain html-tags that are currently not rendering correctly?

For example:

![Screenshot 2021-11-16 at 08 59 42](https://user-images.githubusercontent.com/53602672/141944505-8023b827-572c-4043-8547-6e9336e0a6fc.png)

**Comment by Qonflux** [comment]
Found it hidden in the docs. Here's my code:

```
VMdEditor.xss.extend({
  // extend white list
  whiteList: {
    source: [],
    iframe: ['src'],
    label: []
  },
});
```

**Comment by kofider** [comment]
Please share solution for me. Thanks!
