### ISSUE TITLE
typescript 下编译失败

### ISSUE THREAD

**Issue by rpdg** [code-farmer-i/vue-markdown-editor#14]
![微信截图_20200529142845](https://user-images.githubusercontent.com/1169162/83228674-4f51bd00-a1b9-11ea-80d2-f212dc001213.png)

如图。
理论上在 index.d.ts的倒数第二行前，加个 declare 应该就好了

**Comment by code-farmer-i** [comment]
1.3.1-beta.1 测试包中已调整 可以 install @kangc/v-md-editor@beta 试试，如果没问题的话将在下个正式包修复

**Comment by rpdg** [comment]
beta版经测试，可以编译了，谢谢
