### ISSUE TITLE
图片上传按示例代码拿不到files

### ISSUE THREAD

**Issue by lexiaoyuan** [code-farmer-i/vue-markdown-editor#16]
图片上传按示例代码拿不到files，怎么解决啊？
```js
handleUploadImage(event, insertImage, files) {
      // 拿到 files 之后上传到文件服务器，然后向编辑框中插入对应的内容
      console.log(files)

      // 此处只做示例
      insertImage({
        url:
          'https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1269952892,3525182336&fm=26&gp=0.jpg',
        desc: '七龙珠'
      })
    }
```
`console.log(files)`打印的是undefined

**Comment by lexiaoyuan** [comment]
> 图片上传按示例代码拿不到files，怎么解决啊？
> 
> ```js
> handleUploadImage(event, insertImage, files) {
>       // 拿到 files 之后上传到文件服务器，然后向编辑框中插入对应的内容
>       console.log(files)
> 
>       // 此处只做示例
>       insertImage({
>         url:
>           'https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=1269952892,3525182336&fm=26&gp=0.jpg',
>         desc: '七龙珠'
>       })
>     }
> ```
> 
> `console.log(files)`打印的是undefined

要通过`event.target.files[0]`来拿到

**Comment by code-farmer-i** [comment]
什么版本呀，这个参数是最新版本才加上的

**Comment by code-farmer-i** [comment]
1.3.0版本才有files参数

**Comment by lexiaoyuan** [comment]
> 1.3.0版本才有files参数

哦哦，我的是1.2.13版本
