### ISSUE TITLE
扩展 markdown-it修改a标签的rel无效

### ISSUE THREAD

**Issue by thinkmoon** [code-farmer-i/vue-markdown-editor#165]
使用markdown-it-link-attributes，修改markdown-it
可以修改出了rel以外其他attr，唯独设置rel的时候，页面上直接不显示rel，token数组的attrs数组上都能看到值。
![image](https://user-images.githubusercontent.com/28600813/163843943-7a4ffc5f-bd35-4805-a66e-1e8199992d1d.png)
![image](https://user-images.githubusercontent.com/28600813/163844284-5d01fe9a-546a-4345-9af3-8f4a5783d7c7.png)
![image](https://user-images.githubusercontent.com/28600813/163843990-8f5ebd5d-0a6c-4571-a282-6b733e39c142.png)
直接调用md.render的时候显示了rel，但是使用v-md-preview的时候少了rel属性
![image](https://user-images.githubusercontent.com/28600813/164000526-ee77c7b1-6756-4363-bc32-c8cfb24bf163.png)
![image](https://user-images.githubusercontent.com/28600813/164000595-dc280c2b-4ac6-4869-b8fb-8419b6b1a8ab.png)
![image](https://user-images.githubusercontent.com/28600813/164000648-98c71145-1a98-4244-a950-6d4b6786bcd0.png)

**Comment by thinkmoon** [comment]
问题已解决，未设置白名单

**Comment by hua126mail** [comment]
> 问题已解决，未设置白名单

请问是如何设置白名单的。

我的逻辑是下面这样的，但不生效`VMdPreview.use(githubTheme, {
	Hljs,
	extend(md: any) {
		md.validateLink = function (aa) {
			console.log('🚀 ~ aa:', aa)
			return true
		}
		md.set({
			html: true,
			breaks: true,
			linkify: true
		})
			.use(markdownItAttrs, {
				leftDelimiter: '{',
				rightDelimiter: '}',
				allowedAttributes: []
			})
			.use(mila, {
				attrs: {
					class: 'my-class',
					target: '_blank',
					rel: 'noopener',
					dataAge: '24'
				}
			})`

**Comment by hua126mail** [comment]
> 问题已解决，未设置白名单

请问是如何设置白名单的。我的逻辑是下面这样的，但不生效。
```javascript
import VMdPreview from '@kangc/v-md-editor/lib/preview'
import '@kangc/v-md-editor/lib/style/preview.css'
import githubTheme from '@kangc/v-md-editor/lib/theme/github.js'
import '@kangc/v-md-editor/lib/theme/style/github.css'
import Hljs from 'highlight.js'
import 'highlight.js/styles/monokai.css'
import mila from 'markdown-it-link-attributes'
import markdownItAttrs from 'markdown-it-attrs'

 VMdPreview.use(githubTheme, {
	Hljs,
	extend(md: any) {
		md.set({
			html: true,
			breaks: true,
			linkify: true
		})
			.use(markdownItAttrs, {
				leftDelimiter: '{',
				rightDelimiter: '}',
				allowedAttributes: []
			})
			.use(mila, {
				attrs: {
					class: 'my-class',
					target: '_blank',
					rel: 'noopener',
					dataAge: '24'
				}
			})
		const markdownText = '请点击进入<span dataAge="20" onclick="alert(123)">555</span>'
		const result = md.render(markdownText)
		console.log('🚀 ~ result:', result)
	}
})
```
