### ISSUE TITLE
怎么在前端较好地显示拿到的html代码，高亮代码等

### ISSUE THREAD

**Issue by yzh990918** [code-farmer-i/vue-markdown-editor#17]
我在拿到了md编辑的代码片段后渲染到前端是这样的，样式很难看
![](https://image.yangxiansheng.top/img/20200606002453.png?imagelist)

**Comment by code-farmer-i** [comment]
可以用编辑器的预览模式或者是直接使用预览组件

**Comment by code-farmer-i** [comment]
你是直接存储的html代码？ 建议存储编写的markdown文本，然后用编辑器预览。可以加qq群沟通 798884474

**Comment by yzh990918** [comment]
好的，但是前端调用接口的时候保存的是转译后的html代码，接口返回的也是html片段 @code-farmer-i

**Comment by code-farmer-i** [comment]
一定要存储html代码吗，不能存储markdown文本吗0.0

**Comment by yzh990918** [comment]
好的我跟后端协商一下
