### ISSUE TITLE
vuepress 主题在手机端 显示问题

### ISSUE THREAD

**Issue by ghost** [code-farmer-i/vue-markdown-editor#18]
在手机端 ，图片无法正常， 点击预览图片，也出现不能正常不能 100% 充满

**Comment by ghost** [comment]
GitHub主题则正常

**Comment by code-farmer-i** [comment]
能提供在线预览的地址或者截图吗

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/36656018/83937552-22785800-a800-11ea-8590-998d16c9362c.png)
![2](https://user-images.githubusercontent.com/36656018/83937553-24dab200-a800-11ea-80bd-6d8f099a7010.png)

第一个是github的主题  第二个是vuepress,,   在电脑端 显示也是这样， 还有就是如果是预览组件的话， 如何使用行号插件

**Comment by code-farmer-i** [comment]
图片可以设置宽度的呀 是设置的100%吗

**Comment by code-farmer-i** [comment]
![](){width="100%" height="auto"}

**Comment by code-farmer-i** [comment]
使用插件的方式都是一样的

**Comment by ghost** [comment]
> {width="100%" height="auto"}

请问这个在哪设置呢

**Comment by code-farmer-i** [comment]
\!\[Description](http://){width="100%" height="auto"}

**Comment by ghost** [comment]
> ![Description](http://){width="100%" height="auto"}

现在电脑端可以了，图片点击预览正常，但是在手机端显示预览还是不正常（github主题不用设置宽高，而且预览完全正常）

![3](https://user-images.githubusercontent.com/36656018/83939125-e26ba200-a80c-11ea-9aa8-88cecfb2663b.png)

**Comment by code-farmer-i** [comment]
install @kangc/v-md-editor@beta 安装一个测试包试试

**Comment by code-farmer-i** [comment]
1.3.1版本修复
