### ISSUE TITLE
如何默认关闭预览

### ISSUE THREAD

**Issue by zhanyeye** [code-farmer-i/vue-markdown-editor#19]
大佬，请问如何默认关闭预览呢？

------------------------------

![image](https://user-images.githubusercontent.com/35565811/83946891-30e96280-a846-11ea-8ad2-ada6a6dcded4.png)

**Comment by code-farmer-i** [comment]
设置模式为纯编辑模式，默认出来的就是没有预览的。 \<v-md-editor mode="edit" /> 。

**Comment by zhanyeye** [comment]
谢谢大佬，你的编辑器太好用了，节省了好多时间😍

**Comment by code-farmer-i** [comment]
👀
