### ISSUE TITLE
预览的时候如何监听正文的滚动条

### ISSUE THREAD

**Issue by shanEr-f** [code-farmer-i/vue-markdown-editor#190]
你好，我想问一下预览模式下如何监听到正文部分的滚动，以此来确定滚动到标题的位置，并在目录中的标题有相应的选中效果。

**Comment by kiroog** [comment]
可以自己写一个，维护标题列表，监听滚动，通过计算标题列表的节点距离页面顶部的距离得到当前阅读的章节，高亮选中对应标题
