### ISSUE TITLE
希望在预览模式下也有一个标题导航

### ISSUE THREAD

**Issue by YstDay** [code-farmer-i/vue-markdown-editor#2]
类似于编辑模式的标题导航

**Comment by code-farmer-i** [comment]
有呀，你用[[toc]]插入一个标题导航就行了 [参考](https://code-farmer-i.github.io/vue-markdown-editor/senior/toc.html)

**Comment by YstDay** [comment]
> 有呀，你用[[toc]]插入一个标题导航就行了 [参考](https://code-farmer-i.github.io/vue-markdown-editor/senior/toc.html)

就是希望不用自己插，组件能自带一个，然后在预览模式的时候能随时进行导航，不用回到顶部

**Comment by code-farmer-i** [comment]
> > 有呀，你用[[toc]]插入一个标题导航就行了 [参考](https://code-farmer-i.github.io/vue-markdown-editor/senior/toc.html)
> 
> 就是希望不用自己插，组件能自带一个，然后在预览模式的时候能随时进行导航，不用回到顶部



> > 有呀，你用[[toc]]插入一个标题导航就行了 [参考](https://code-farmer-i.github.io/vue-markdown-editor/senior/toc.html)
> 
> 就是希望不用自己插，组件能自带一个，然后在预览模式的时候能随时进行导航，不用回到顶部

你说的是那种悬浮在页面上的锚点组件吧😱

**Comment by YstDay** [comment]
> > > 有呀，你用[[toc]]插入一个标题导航就行了 [参考](https://code-farmer-i.github.io/vue-markdown-editor/senior/toc.html)
> > 
> > 
> > 就是希望不用自己插，组件能自带一个，然后在预览模式的时候能随时进行导航，不用回到顶部
> 
> > > 有呀，你用[[toc]]插入一个标题导航就行了 [参考](https://code-farmer-i.github.io/vue-markdown-editor/senior/toc.html)
> > 
> > 
> > 就是希望不用自己插，组件能自带一个，然后在预览模式的时候能随时进行导航，不用回到顶部
> 
> 你说的是那种悬浮在页面上的锚点组件吧

是的，而且可以控制显示和关闭

**Comment by code-farmer-i** [comment]
可以参考[自定义锚点](https://code-farmer-i.github.io/vue-markdown-editor/senior/anchor.html)的原理来实现。
