### ISSUE TITLE
使用自定义锚点时出现preview.scrollToTarget is not a function问题

### ISSUE THREAD

**Issue by Samuel-wyj** [code-farmer-i/vue-markdown-editor#215]
使用自定义锚点时出现preview.scrollToTarget is not a function问题

**Comment by yamonc** [comment]
> 使用自定义锚点时出现preview.scrollToTarget is not a function问题

我也一样哇。这个为什么这么多坑哇。

**Comment by yiyuqi** [comment]
官网的没问题，你用的是vue2还是vue3

**Comment by Samuel-wyj** [comment]
> 

vue2

**Comment by code-farmer-i** [comment]
<img width="616" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/15082905/1d888609-2b2e-4c0b-bacd-9bb57107b0bd">
