### ISSUE TITLE
无法解析不带/等开头路径的图片，是否是有意为之？

### ISSUE THREAD

**Issue by cejune** [code-farmer-i/vue-markdown-editor#216]
markdown语法如下
```
#图片
![](http://localhost:4001/favicon.png)
![](favicon.png)
![](/favicon.png)
![](./favicon.png)
```
第二种是无法解析的，虽然可以写成后两种，但是是否需要支持第二种，这种写法还是存在的
![WX20230202-234613](https://user-images.githubusercontent.com/117468581/216372343-6a97ec77-ca24-4359-900b-b0b7d3cf0bb3.png)

**Comment by mxluomx** [comment]
我也遇到了这种，你怎么解决的呢

**Comment by code-farmer-i** [comment]
实际是xss做了href的安全过滤，不包含协议的链接路径默认被过滤，可以通过自定义xss的配置来实现。实例如下：
```js
// 该示例展示了当a标签href的值为123时，返回它的值。
VueMarkdownEditor.xss.extend({
  safeAttrValue(tag, name, value) {
    console.log(tag, name, value);
    if (tag === 'a') {
      if (name === 'href') {
        if (value === '123') return value;
      }
    }
  },
});
```
xss 官方 issuse: https://github.com/leizongmin/js-xss/issues/118
