### ISSUE TITLE
去官方下载，https://prismjs.com/download.html，勾选你需要的语言包，然后引入下载下来的js即可

### ISSUE THREAD

**Issue by wuye251** [code-farmer-i/vue-markdown-editor#231]
去官方下载，https://prismjs.com/download.html，勾选你需要的语言包，然后引入下载下来的js即可

_Originally posted by @w6990548 in https://github.com/code-farmer-i/vue-markdown-editor/issues/33#issuecomment-663406241_

**Comment by wuye251** [comment]
<img width="691" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/24435699/1336fac8-cdd8-4516-8558-e9e0c4f5d50e">

如何使用自己下载下的js文件呢?  有懂哥给小白教下吗

**Comment by wuye251** [comment]
https://code-farmer-i.github.io/vue-markdown-editor/zh/question.html#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B8%B2%E6%9F%93%E6%A0%B7%E5%BC%8F 在这里找到了相关方法

<img width="735" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/24435699/e5358b78-7be2-4ecf-a605-758cbf7acb82">

是有变化，但是我添加的自定义配置项没有生效，比如:代码复制的按钮没出来

**Comment by wuye251** [comment]
<img width="481" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/24435699/6536d2ae-2234-4394-8f1f-d4da340781c1">

改成这样之后  go/css还有我包含下载的一些语言高亮可以了(现在还不确定是我下载的自定义js代码起的效果), 但代码行数,复制代码 还没出现

**Comment by code-farmer-i** [comment]
http://ckang1229.gitee.io/vue-markdown-editor/zh/theme/vuepress.html#%E6%89%A9%E5%B1%95%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE%E8%AF%AD%E8%A8%80%E5%8C%85
