### ISSUE TITLE
列表前面的序号不显示，只显示空格

### ISSUE THREAD

**Issue by 1635016329** [code-farmer-i/vue-markdown-editor#232]
![Snipaste_2023-05-13_12-40-30](https://github.com/code-farmer-i/vue-markdown-editor/assets/98443444/011e25a7-a0d4-49d2-ad27-9c56de7b6a33)
列表前面的序号不显示，只显示空格，求解！

**Comment by code-farmer-i** [comment]
ul和ol的样式被项目中的全局样式重置掉了
