### ISSUE TITLE
使用预览组件，该怎么把toc和正文分开渲染？

### ISSUE THREAD

**Issue by GLORYFeonix** [code-farmer-i/vue-markdown-editor#239]
想要跟编辑器组件一样，toc在侧面

**Comment by code-farmer-i** [comment]
可以参考文档[自定义锚点](https://ckang1229.gitee.io/vue-markdown-editor/zh/senior/anchor.html)的逻辑实现一个导航，还有另外一个办法，就是使用编辑器组件，设置组件props: mode="preview", default-show-toc="true"，然后通过css把顶部操作栏给隐藏掉并微调样式，这样应该可是可行的，效果如下：
<img width="739" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/15082905/71c32127-293d-40ea-a491-3c1a894d2466">
