### ISSUE TITLE
希望能在鼠标hover到代码块能在右上角出现复制内容

### ISSUE THREAD

**Issue by ashuicoder** [code-farmer-i/vue-markdown-editor#24]
希望能在鼠标hover到代码块能在右上角出现复制内容，然后点击就会复制当前代码块解析好的代码

**Comment by code-farmer-i** [comment]
1.4.3版本 已增加相关功能的插件，具体参考[copy code plugin](https://code-farmer-i.github.io/vue-markdown-editor/zh/plugins/copy-code.html)
