### ISSUE TITLE
在预览模式下遇到style标签显示出现问题

### ISSUE THREAD

**Issue by Nciae-Zyh** [code-farmer-i/vue-markdown-editor#245]
我的内容数据如下{在HTML中，CSS的优先级是指浏览器在解析CSS样式时，决定哪个样式规则应用于哪个元素的一种规则。CSS的优先级取决于样式声明的特定组合，而不是简单地根据样式声明的数量来决定。

CSS的优先级按照以下顺序来决定：

1. 内联样式（Inline Style）：在HTML元素的style属性中直接定义的样式具有最高的优先级。它会覆盖任何其他方式定义的样式。

2. 内部样式表（Internal Style Sheet）：在HTML文件的<head>标签内使用<style>标签定义的样式具有次高的优先级。它会覆盖外部样式表中相同选择器的样式。

3. 外部样式表（External Style Sheet）：外部CSS文件中定义的样式具有较低的优先级。它将会被内联样式和内部样式表覆盖。

4. 浏览器默认样式：如果没有定义任何CSS样式，浏览器会使用其默认样式。

在以上规则中，相同优先级的样式将按照样式表中的顺序来应用。如果多个样式具有相同的优先级且应用在同一个元素上，最后一个定义的样式将会被应用。

此外，还可以通过使用!important标记来提高具体样式的优先级。将!important应用于一个样式声明，会使该样式具有最高的优先级，即使它在CSS样式表中定义的位置较低。但是应该避免滥用!important，应该优先考虑更具体的选择器来解决样式冲突的问题。}
但其在组件中显示的情况如下图
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/75648776/b941af70-3226-4762-9743-28a5ab2f7d39)
希望可以增加一个style标签不进行渲染的功能。

**Comment by code-farmer-i** [comment]
转义一下就好了 
<img width="807" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/15082905/39b24f4d-2f7a-45a7-95da-f2fece0043f8">

**Comment by Nciae-Zyh** [comment]
您好，我的内容为chatgpt自动生成的内容，通过websocket进行传输，所以使用转义来规避markdown自动翻译较为繁琐，若后端将<转义为\\\<可能会造成不必要的风险。

**Comment by code-farmer-i** [comment]
配置一下 markdown-it 关闭 html 试试 
```js
VueMarkdownEditor.use(vuepressTheme, {
  extend(md) {
    // md为 markdown-it 实例，可以在此处进行修改配置,并使用 plugin 进行语法扩展
    md.set({
      html: false
    });
  },
});
```

**Comment by Nciae-Zyh** [comment]
已解决，谢谢！
