### ISSUE TITLE
Don't work codemirror-editor

### ISSUE THREAD

**Issue by lexfoxer** [code-farmer-i/vue-markdown-editor#25]
Hi, thanks for the editor!
There was an error using __codemirror editor__, can you tell me how to solve it?  

I am using example code from:
https://code-farmer-i.github.io/vue-markdown-editor/examples/codemirror-editor.html  

Error text:
```bash
This dependency was not found:

* @kangc/v-md-editor/codemirror-editor in ./src/main.js

To install it, you can run: npm install --save @kangc/v-md-editor/codemirror-editor
```

**Comment by code-farmer-i** [comment]
The import path of the sample code of the document is wrong and has been fixed.
