### ISSUE TITLE
除了点击清空按钮，有没有给出供父组件直接调用的清空输入区的api？

### ISSUE THREAD

**Issue by nexttime8** [code-farmer-i/vue-markdown-editor#250]
`
toolbar: {
        customToolbar: {
          icon: 'toolbar图标类名',
          title: 'hover时显示的标题',
          action(editor) {
            // toolbar点击时触发的函数
          },
        },
      },
`
只找到自定义工具栏，知道点击toolbar需要触发一定的函数，有没有具体的供父组件使用的api。
因为我想把编辑框作为表单的一部分，在表单提交的时候验证，并且能够一键重置。

**Comment by code-farmer-i** [comment]
editor.execCommand('clear');
