### ISSUE TITLE
预览能不能支持识别 ** ✓ ** 并显示为加粗

### ISSUE THREAD

**Issue by six-u** [code-farmer-i/vue-markdown-editor#256]
** ✓ ** 勾号两遍有空格，加粗就不生效
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/49940186/3bbfe16c-0772-4669-9cfc-7a669ff180b9)

**Comment by ZGW99** [comment]
这没问题，语法规定中间不应该有空格，如果想加空格在*两侧加

**Comment by six-u** [comment]
感谢，如果我能编辑内容的话，这当然有用。可是我不能编辑已有的内容，不知道有没有其他方式可以进行处理这种问题？
