### ISSUE TITLE
希望加入标题序号

### ISSUE THREAD

**Issue by ashuicoder** [code-farmer-i/vue-markdown-editor#26]
1. xxxxxxx
1.1 xxxxxxxxxxxxx
2 xxxxxxxxxxxx
2.1 xxxxxxxxxxxxx

**Comment by code-farmer-i** [comment]
目录导航？

**Comment by lsw9521** [comment]
> 目录导航？

我觉得这个不是要目录导航，应该是要自动标题序号，就像 Vnote 里的标题自动编号一样，这样移动或者在两个标题之间插入新的段落，就不用每次都自己去维护标题的编号了
