### ISSUE TITLE
复制按钮没反应，而且加了复制之后显示行数消失

### ISSUE THREAD

**Issue by tingbeauty** [code-farmer-i/vue-markdown-editor#263]
<img width="804" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/35484526/bb7d222b-1c83-45d8-9d2f-760027c3d286">
<img width="339" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/35484526/8e835fc4-69b3-401b-8651-c8f833c9d927">
<img width="346" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/35484526/61ab4d75-c18a-4b1f-ab03-43ff3b737416">
![Uploading image.png…]()
点击复制打印不生效，多点几次又会生效

**Comment by tingbeauty** [comment]
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/35484526/dd31f35c-a8f5-4204-8514-96c8b01944ad)
复制和行数显示不能共存

**Comment by code-farmer-i** [comment]
没引插件样式吧。。
