### ISSUE TITLE
预览组件样式解析问题

### ISSUE THREAD

**Issue by ashuicoder** [code-farmer-i/vue-markdown-editor#27]
1. 分割线会使上一行的字体加粗，如果加一行空行就不会，但是在预览组件上不解析空行 。

2. “-”手敲的无序列表在预览组件上不显示

**Comment by code-farmer-i** [comment]
是要加一个空行，其他的问题没有复现。。

**Comment by ashuicoder** [comment]
VMdPreview 手敲的无序列表在预览组件上不显示项目前面的小圆圈，但是VMdEditor的预览能显示

**Comment by code-farmer-i** [comment]
能提供复现代码吗

**Comment by ashuicoder** [comment]
后台渲染没问题
![后台](https://blog-szy-1300654851.cos.ap-shanghai.myqcloud.com/assets/Screenshot.png)
前台用`VMdPreview`列表前面的圆圈不见了
![前台](https://blog-szy-1300654851.cos.ap-shanghai.myqcloud.com/QQ%E6%88%AA%E5%9B%BE20200709115100.png)

**Comment by code-farmer-i** [comment]
看下是不是ul样式被污染了

**Comment by ashuicoder** [comment]
看了下这个按钮用的是原生的`list-style`，但是我觉得这样是不对的啊，好多网站都用了`reset.css`，直接干掉`list-style`了，所以我觉得插件样式里得加一下

**Comment by code-farmer-i** [comment]
em strong 很多样式都会被重置，这些都是直接使用的浏览器默认样式，不会定义
