### ISSUE TITLE
vue2 引入了Katex 插件 但是不起作用

### ISSUE THREAD

**Issue by 18237966658** [code-farmer-i/vue-markdown-editor#272]
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/50265705/a86dbbe5-d685-4e45-a522-ffbb67da64f6)
我在 main.js中引入了 公式插件但是并没有起到作用，请问是哪里的问题？
import createKatexPlugin from '@kangc/v-md-editor/lib/plugins/katex/cdn';
VMdEditor.use(createKatexPlugin());

Vue.use(VMdEditor);

![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/50265705/fcf15e9d-426d-4129-8641-675a6e06bc65)

**Comment by 18237966658** [comment]
忘了，要在 public->index.html 加入
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js"></script>

**Comment by pengxinyin** [comment]
这个插件可以显示echarts图表么？我试了一下不能正确显示
