### ISSUE TITLE
报错 base-editor.js:9054  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'registerHotkeys')

### ISSUE THREAD

**Issue by gkyCode** [code-farmer-i/vue-markdown-editor#278]
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/97236549/0bf2e1fa-729a-4eb7-97f8-ecec2fa718f3)
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/97236549/2c73ca50-ee9a-44fc-8efd-94b07b7819f4)
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/97236549/008bef37-cb9d-4364-9250-b22c2b7cc2f8)
![image](https://github.com/code-farmer-i/vue-markdown-editor/assets/97236549/b59400bc-8f41-423d-a5a7-e67683d3ba02)

qi前一段时间使用 没有出现 该问题 最近打开页面突然报错 以上是环境 引入方式参考文档

**Comment by kf0509** [comment]
遇到了同样的问题

**Comment by SmallBai22** [comment]
我才下载 的使用 的， 轻量版报这个错。进阶版 不报错。 不显示内容

**Comment by code-farmer-i** [comment]
这个问题我没有复现，可以上传一个能复现的仓库，我看看什么引起的

**Comment by jihao** [comment]
vue2     "@kangc/v-md-editor": "^1.7.12", 一开始也是报同样的错误

解决方式，npm run dev 重启，然后就好了 🤣

**Comment by LLawlight** [comment]
> 这个问题我没有复现，可以上传一个能复现的仓库，我看看什么引起的

把vue升级到3.4.24就会出现这个问题了，3.2+没有问题

**Comment by klim09** [comment]
Component is unusable on 3.4. :(

**Comment by RUBisco0211** [comment]
3.4.x上报这个错

**Comment by Charmnut** [comment]
vue2 "@kangc/v-md-editor": "^1.7.12" 遇到同样的问题

**Comment by ynzion** [comment]
删掉 node_modules 重新npm -i 解决了
