### ISSUE TITLE
版本 1.2.7 import '@kangc/v-md-editor/lib/style/editor.css'; 不存在

### ISSUE THREAD

**Issue by YstDay** [code-farmer-i/vue-markdown-editor#3]
在[文档：快速上手](https://code-farmer-i.github.io/vue-markdown-editor/quick-start.html#%E5%AE%89%E8%A3%85)中

`import '@kangc/v-md-editor/lib/style/editor.css';`
上述资源不存在

**Comment by code-farmer-i** [comment]
@kangc/v-md-editor/lib/style/base-editor.css  文档错了，到时候修复一下
