### ISSUE TITLE
本地上传的图片对象怎么获得？

### ISSUE THREAD

**Issue by QQchu** [code-farmer-i/vue-markdown-editor#30]
![image](https://user-images.githubusercontent.com/42673687/86896829-2e29a800-c139-11ea-9e2e-8ce103d59272.png)

**Comment by code-farmer-i** [comment]
files就是文件对象数组

**Comment by QQchu** [comment]
> files就是文件对象数组


在你文档演示里面，也是一个字符串数组

**Comment by QQchu** [comment]
> > files就是文件对象数组
> 
> 在你文档演示里面，也是一个字符串数组

![image](https://user-images.githubusercontent.com/42673687/86983692-201e6a80-c1bf-11ea-81ec-e2b5d83e8ab1.png)

**Comment by code-farmer-i** [comment]
嗯，是因为1.4.2版本兼容ie调整代码引起的bug，[1.4.4版本](https://code-farmer-i.github.io/vue-markdown-editor/zh/changelog.html#_1-4-4)修复。
