### ISSUE TITLE
希望加上图片文字环绕～不然图片都按编辑区域werth的100%显示，图片会太大，失真

### ISSUE THREAD

**Issue by QQchu** [code-farmer-i/vue-markdown-editor#31]

**Comment by code-farmer-i** [comment]
图片的width可以设置，只是默认值是100%

**Comment by QQchu** [comment]
> 图片的width可以设置，只是默认值是100%

是可以但是图片还是会独占一行

**Comment by code-farmer-i** [comment]
![image](https://user-images.githubusercontent.com/15082905/87003480-4f000500-c1ee-11ea-80fe-89fc14615f96.png)
