### ISSUE TITLE
主题扩展包，单独引入 prism-php，会出现 Cannot read property 'tokenizePlaceholders' of undefined"，且无法切换到其他语言，代码块无法正常显示

### ISSUE THREAD

**Issue by ShiTouSan** [code-farmer-i/vue-markdown-editor#32]
![image](https://user-images.githubusercontent.com/28656326/88272960-12fb9280-cd0c-11ea-9285-a6384a6e53e2.png)

![image](https://user-images.githubusercontent.com/28656326/88273018-26a6f900-cd0c-11ea-8e85-967f66e38970.png)

![image](https://user-images.githubusercontent.com/28656326/88273054-3292bb00-cd0c-11ea-923d-f64dc2506d11.png)

**Comment by code-farmer-i** [comment]
参考[issues](https://github.com/code-farmer-i/vue-markdown-editor/issues/23#issue-647431644)
