### ISSUE TITLE
快捷复制代码

### ISSUE THREAD

**Issue by beloved-zh** [code-farmer-i/vue-markdown-editor#33]
找了好久的基于vue的编辑器就这个比较满意，使用方便，文档详细。
感谢作者

------------------------------------
快捷复制代码有问题
编辑组件点击
会在当前地址拼接参数`?file`
预览组件点击没有反应
所有都不能复制不上
```js
import VMdEditor from '@kangc/v-md-editor/lib/codemirror-editor'
import '@kangc/v-md-editor/lib/style/codemirror-editor.css'
import vuepressTheme from '@kangc/v-md-editor/lib/theme/vuepress.js' // 主题
VMdEditor.use(vuepressTheme)

import createCopyCodePlugin from '@kangc/v-md-editor/lib/plugins/copy-code/index'
VMdEditor.use(createCopyCodePlugin())
```

------------------------------------

有没有什么方法可以一次导入所有代码高亮的语言包

**Comment by ShiTouSan** [comment]
去官方下载，https://prismjs.com/download.html，勾选你需要的语言包，然后引入下载下来的js即可

**Comment by code-farmer-i** [comment]
[1.4.8](https://code-farmer-i.github.io/vue-markdown-editor/zh/changelog.html#_1-4-8)版本已修复

**Comment by beloved-zh** [comment]
```bash
npm i @kangc/v-md-editor -S
```
下载的还是1.4.7版本
![image](https://user-images.githubusercontent.com/52067640/88394742-84ae0c00-cdf2-11ea-829a-79abcff8a486.png)
手动在`package.json`文件修改版本为1.4.8也下载不来

---

顺便在问下作者
vuepress主题或者github主题，下载的代码高亮包，怎么引入全部语言的
![image](https://user-images.githubusercontent.com/52067640/88395123-22a1d680-cdf3-11ea-9beb-6527674f2c8c.png)

**Comment by beloved-zh** [comment]
> [1.4.8](https://code-farmer-i.github.io/vue-markdown-editor/zh/changelog.html#_1-4-8)版本已修复

```bash
npm i @kangc/v-md-editor -S
```
下载的还是1.4.7版本
![image](https://user-images.githubusercontent.com/52067640/88394742-84ae0c00-cdf2-11ea-829a-79abcff8a486.png)
手动在`package.json`文件修改版本为1.4.8也下载不来

---

顺便在问下作者
vuepress主题或者github主题，下载的代码高亮包，怎么引入全部语言的
![image](https://user-images.githubusercontent.com/52067640/88395123-22a1d680-cdf3-11ea-9beb-6527674f2c8c.png)

**Comment by code-farmer-i** [comment]
npm延迟吧，语言包的上面有人说了啊

**Comment by wuye251** [comment]
> 去官方下载，[https://prismjs.com/download.html，勾选你需要的语言包，然后引入下载下来的js即可](https://prismjs.com/download.html%EF%BC%8C%E5%8B%BE%E9%80%89%E4%BD%A0%E9%9C%80%E8%A6%81%E7%9A%84%E8%AF%AD%E8%A8%80%E5%8C%85%EF%BC%8C%E7%84%B6%E5%90%8E%E5%BC%95%E5%85%A5%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E7%9A%84js%E5%8D%B3%E5%8F%AF)
<img width="691" alt="image" src="https://github.com/code-farmer-i/vue-markdown-editor/assets/24435699/1336fac8-cdd8-4516-8558-e9e0c4f5d50e">
如何使用自己下载下的js文件呢?
