### ISSUE TITLE
不是很理解 model 的作用，没有出现效果，希望能够解答一下

### ISSUE THREAD

**Issue by ShiTouSan** [code-farmer-i/vue-markdown-editor#34]
> `mode`
`类型：String`
`默认值: editable`
`模式。可选值：edit(纯编辑模式) editable(编辑与预览模式) preview(纯预览模式)。`

我的代码如下：
> <template>
    <v-md-editor v-model="contents" model="edit"/>
</template>

但实际却没有效果
![image](https://user-images.githubusercontent.com/28656326/88373797-130e9780-cdcb-11ea-972e-909ed6cdd708.png)

**Comment by beloved-zh** [comment]
`mode="edit"`不是`model="edit"`

**Comment by ShiTouSan** [comment]
> `mode="edit"`不是`model="edit"`

哈哈哈哈，我的锅
