### ISSUE TITLE
Copy Code 快捷复制代码，代码可以复制到，但是总是会跳转刷新一次本页面

### ISSUE THREAD

**Issue by ShiTouSan** [code-farmer-i/vue-markdown-editor#35]
如题
![5704aba6-d357-4fcd-a6e8-821aaa1be163](https://user-images.githubusercontent.com/28656326/88380071-70f4ac80-cdd6-11ea-9654-7f234ccc7133.gif)

**Comment by code-farmer-i** [comment]
下个版本优化，目前先可以通过阻止表单submit事件的默认行为来解决

**Comment by code-farmer-i** [comment]
[1.4.8](https://code-farmer-i.github.io/vue-markdown-editor/zh/changelog.html)版本已修复
