### ISSUE TITLE
npm下载问题

### ISSUE THREAD

**Issue by beloved-zh** [code-farmer-i/vue-markdown-editor#36]
都四天了
npm下载的还是1.4.7版本
最新版本还是下载不下来
![image](https://user-images.githubusercontent.com/52067640/88632401-1c0eaa00-d0e6-11ea-8d40-cf234c4cac74.png)
![image](https://user-images.githubusercontent.com/52067640/88632446-2b8df300-d0e6-11ea-8858-f50154e7a342.png)

**Comment by code-farmer-i** [comment]
额 我这边是能下到1.4.8的

**Comment by code-farmer-i** [comment]
你用的是npm 还是 cnpm？

**Comment by beloved-zh** [comment]
一直用npm！现在好了
这几天一直下载不下来，中午那会也下载不下来，现在可以了

----
我又发现个bug。哈哈哈哈。
编辑模式嵌套在form的好了，可以复制代码
预览模式还是复制不上
我是嵌套在`<el-dialog>`标签里的
不知道是不是我写的问题
![image](https://user-images.githubusercontent.com/52067640/88655039-c1367c00-d100-11ea-936d-0d6b11bf6988.png)

![image](https://user-images.githubusercontent.com/52067640/88655127-e88d4900-d100-11ea-9d2c-ef774a7979f6.png)

**Comment by code-farmer-i** [comment]
😅

**Comment by code-farmer-i** [comment]
加qq群讨论吧

**Comment by beloved-zh** [comment]
不知道呀

**Comment by code-farmer-i** [comment]
readme里面写了

**Comment by beloved-zh** [comment]
好的，谢谢
