### ISSUE TITLE
👨🏻‍💻👩🏻‍💻欢迎加入 v-md-editor 交流群 🎉🎉🎉

### ISSUE THREAD

**Issue by code-farmer-i** [code-farmer-i/vue-markdown-editor#37]
QQ群：798884474

**Comment by smz440** [comment]
I'm a beginner of github, so I apologize for any mistakes of usage.
First of all, Thank you for your cool editor. It is just what i wanted.

I have one question.
Can I put TOC panel to preview mode editor?
 If i can, please let me know how to add TOC pane to only Preview mode editor.
* TOC | EDITOR | PREVIEW. 3 panels available
* TOC | PREVIEW. 2 panels i want.

Thank you!

===Update===
If i add `display:none' to .v-md-editor--editable .v-md-editor__editor-wrapper, 2 panes(toc and preview) mode is available. But this is not so elegant i think.

**Comment by nologgg** [comment]
您好，这个qq群满员了，请问还有其它交流群吗？

**Comment by Yaozongbin0828** [comment]
您好，这个qq群满员了，请问还有其它交流群吗？

**Comment by Masterxiechengxun** [comment]
交流群已经满员了
![截屏2024-12-26 10 43 06](https://github.com/user-attachments/assets/bb9d937d-c3e4-4d92-ab54-6ca87e6e1875)

**Comment by list12318** [comment]
![Image](https://github.com/user-attachments/assets/94efd612-7a52-4b13-8f3a-9e0d9d1c8ee3)

你好，满员了，还有其他群吗？
