### ISSUE TITLE
codemirror "change" 事件可以添加 debounce 函数，避免内容过多更新时造成的卡顿问题

### ISSUE THREAD

**Issue by Jesonhu** [code-farmer-i/vue-markdown-editor#4]
简单看了下代码，学了很多东西，但是发现有个问题：

+ https://github.com/code-farmer-i/vue-markdown-editor/blob/dev/src/codemirror-editor.vue#L93

这里需要加上防抖函数，避免内容过多更新时造成的卡顿问题。

**Comment by code-farmer-i** [comment]
加防抖，v-model拿不到实时更新的内容
