### ISSUE TITLE
vue3版什么时候出~

### ISSUE THREAD

**Issue by wxzgis** [code-farmer-i/vue-markdown-editor#42]

**Comment by code-farmer-i** [comment]
国庆有时间的话就搞吧

**Comment by wxzgis** [comment]
> 国庆有时间的话就搞吧

期待，加油

**Comment by code-farmer-i** [comment]
已发布支持vue3的版本 [查看相关文档](http://ckang_1229.gitee.io/vue-markdown-editor/zh/quick-start.html#%E5%AE%89%E8%A3%85%E6%94%AF%E6%8C%81-vue3-%E7%9A%84%E7%89%88%E6%9C%AC)
