### ISSUE TITLE
内置的 codemirror 能不能支持 vim 模式

### ISSUE THREAD

**Issue by lsw9521** [code-farmer-i/vue-markdown-editor#43]
我想要用 vue-markdown-editor 写一个自己用的笔记软件， 其它还好，但是发现 codemirror 的配置对象不支持 vim 的 keymap . 好像是因为 Ediver.vue 中没有引入 'codemirror/keymap/vim.js' 导致的， 能不能更新一下。还有初始化编辑器的时候，没有默认全屏的配置项，能不能也一起加上呢，谢谢 ^_^

**Comment by code-farmer-i** [comment]
你可以试试在引入编辑器之后import 'codemirror/keymap/vim';

**Comment by lsw9521** [comment]
引入 import 'codemirror/keymap/vim'; 还是不行的，刚刚试了下，还有什么细节需要注意的吗？

**Comment by lsw9521** [comment]
> 你可以试试在引入编辑器之后import 'codemirror/keymap/vim';

引入 import 'codemirror/keymap/vim'; 还是不行的，刚刚试了下，还有什么细节需要注意的吗？

**Comment by lsw9521** [comment]
> 你可以试试在引入编辑器之后import 'codemirror/keymap/vim';
要不你直接在 demo 里增加一个 vim 模式的样例吧，麻烦了，谢谢！

**Comment by code-farmer-i** [comment]
你截图一下你的代码

**Comment by lsw9521** [comment]
> 你截图一下你的代码

<template>
  <v-md-editor v-model="text" mode="edit" autofocus :codemirrorConfig="editConfig"
               @change="change()" @save="save()" @keydown.ctrl.p.native.prevent="preview()">
  </v-md-editor>
</template>

<script>
import Vue from 'vue';
import VMdEditor from '@kangc/v-md-editor/lib/codemirror-editor';
import '@kangc/v-md-editor/lib/style/codemirror-editor.css';
import githubTheme from '@kangc/v-md-editor/lib/theme/github.js';
import java from 'highlight.js/lib/languages/java';
import 'codemirror/keymap/vim'

VMdEditor.use(githubTheme, {
  extend(md, hljs) {
    hljs.registerLanguage('java', java);
  }
});

Vue.use(VMdEditor);
export default {
  name: "Markdown",
  data() {
    return {
      text: '',
      editConfig: {
        tabSize: 4,
        lineNumbers: true,
        styleActiveLine: true,
        ...this.codemirrorConfig,
        value: this.text,
        mode: 'markdown',
        lineWrapping: 'wrap',
        scrollbarStyle: 'overlay',
        dragDrop: false,
        keyMap:"vim",
      }
    };
  },
  methods: {
    change: function () {
      console.info(this.text)
    },
    save: function () {
      console.info(this.text)
    },
    preview: function () {
      console.info("preview")
    }
  }
}
</script>

<style scoped>

</style>

**Comment by code-farmer-i** [comment]
能截图吗 我这怎么看 - -

**Comment by lsw9521** [comment]
> 能截图吗 我这怎么看 - -

![image](https://user-images.githubusercontent.com/64994513/95966025-3b8fb600-0e3d-11eb-9800-360c76fc4a61.png)
![image](https://user-images.githubusercontent.com/64994513/95966054-434f5a80-0e3d-11eb-95ea-904a1c48dfbe.png)

**Comment by lsw9521** [comment]
> 能截图吗 我这怎么看 - -

只要把 keyMap : "vim" 这一行配置删掉就能正常初始化编辑器，加上就不可以了

**Comment by code-farmer-i** [comment]
我这边试了好像可以 控制台有报错吗？

**Comment by code-farmer-i** [comment]
import VMdEditor from '@kangc/v-md-editor/src/codemirror-editor'; 你引这个试试

**Comment by lsw9521** [comment]
> import VMdEditor from '@kangc/v-md-editor/src/codemirror-editor'; 你引这个试试

不行哦，直接用这个编译都通不过了

你直接在自己的项目里引入 import 'codemirror/keymap/vim'; 应该是没问题的， 但是如果我是引用你的项目，然后再自己引入 import 'codemirror/keymap/vim'; 可能就是不行的，因为你的项目里原来就没有引入过 'codemirror/keymap/vim'; 说的有点乱，我是这么猜的

**Comment by lsw9521** [comment]
> import VMdEditor from '@kangc/v-md-editor/src/codemirror-editor'; 你引这个试试

需要在你的项目里引入  import 'codemirror/keymap/vim';  然后别人直接引用你的项目可能就可以了

**Comment by code-farmer-i** [comment]
我打算把codemirror编辑器插件相关的资源引入和配置管理全部开放给用户 避免以后有类似的需求 下个版本更新吧

**Comment by lsw9521** [comment]
> 我打算把codemirror编辑器插件相关的资源引入和配置管理全部开放给用户 避免以后有类似的需求 下个版本更新吧

辛苦了

**Comment by code-farmer-i** [comment]
你的方案只能解决你的需求，并且对于大部分没有你这个需求的用户来说，引入了冗余的资源，不太好

**Comment by code-farmer-i** [comment]
发版了 1.5.0 [更新日志](http://ckang_1229.gitee.io/vue-markdown-editor/zh/changelog.html#_1-5-0-2-1-0)

**Comment by lsw9521** [comment]
> 发版了 1.5.0 [更新日志](http://ckang_1229.gitee.io/vue-markdown-editor/zh/changelog.html#_1-5-0-2-1-0)

谢谢！辛苦！辛苦！加油！

**Comment by lsw9521** [comment]
> 发版了 1.5.0 [更新日志](http://ckang_1229.gitee.io/vue-markdown-editor/zh/changelog.html#_1-5-0-2-1-0)

能不能把全屏选项也添加到 props 里，每次要自己点一下感觉也挺多余的

**Comment by lsw9521** [comment]
> 发版了 1.5.0 [更新日志](http://ckang_1229.gitee.io/vue-markdown-editor/zh/changelog.html#_1-5-0-2-1-0)

退出全屏的快捷键能不能自己配置呀？ Vim 模式默认进入 normal 模式的快捷键是 Esc ，这样一来经常不自觉的就退出全屏了

**Comment by code-farmer-i** [comment]
你可以在mounted 里面 window.removeEventListener('keyup', this.$refs.editor.handleWindowKeyup, false); 把这个事件解绑 esc就不会关闭全屏了

**Comment by code-farmer-i** [comment]
[是否默认开启全屏](http://ckang_1229.gitee.io/vue-markdown-editor/zh/api.html#default-fullscreen)
