### ISSUE TITLE
vue 3 中 工具栏按钮点击无效

### ISSUE THREAD

**Issue by peakDragonCheung** [code-farmer-i/vue-markdown-editor#50]
在vue 3.0 vite 工具中使用 点击按钮无效，只能使用 键盘快捷键，

**Comment by peakDragonCheung** [comment]
经过我跟踪你们的源码实现形式，发现 $emit('toolbar-menu-click', arguments[0]) 这一句代码 在vue3 中会有warning 且传递的参数并不是arguments[0]  参数的第一个，而是代理的实例，不建议这么写法，因为现在都是 Proxy 形式可能导致问题。

**Comment by code-farmer-i** [comment]
https://github.com/vuejs/vue-next/issues/2526

**Comment by rieval** [comment]
同样的问题，vite 3.0.4

没有解决办法吗？

**Comment by code-farmer-i** [comment]
确认 vue 的版本与 @vue/compiler-sfc 的版本一致

**Comment by rieval** [comment]
> 确认 vue 的版本与 @vue/compiler-sfc 的版本一致

![屏幕截图 2020-12-03 151453](https://user-images.githubusercontent.com/22883406/100976650-cc039080-357a-11eb-9302-57555b6825b5.png)

![屏幕截图 2020-12-03 151536](https://user-images.githubusercontent.com/22883406/100976659-cefe8100-357a-11eb-8d15-353dd3b11198.png)

看了下 `package-lock.json` 里的确实也都是 `3.0.4`

我点击工具栏的时候也没出现 log，单单只是没反应

**Comment by code-farmer-i** [comment]
应该就是这个问题吧 我之前也遇到了 同步版本之后就行了

**Comment by rieval** [comment]
> 应该就是这个问题吧 我之前也遇到了 同步版本之后就行了

我试着移除这两个包，然后再安装 `3.0.3` 版本的，还是不行，很迷惑

大佬有时间可以用 vite 脚手架再试一次吗，如果无法复现那就是我自己的问题了 😂😂

**Comment by code-farmer-i** [comment]
好的

**Comment by code-farmer-i** [comment]
你装一下这个试试 yarn add @kangc/v-md-editor@2.1.6-beta.2

**Comment by code-farmer-i** [comment]
很奇怪，2.1.5的版本好像有这个问题，2.1.6的测试包又没有，但是2.1.6版本我并没有做什么改动- -！

**Comment by rieval** [comment]
> 你装一下这个试试 yarn add @kangc/v-md-editor@2.1.6-beta.2

安装了 `2.1.6-beta.2` 后问题解决了，感谢 🤣

**Comment by code-farmer-i** [comment]
嗯嗯，明天发2.1.6的正式包
