### ISSUE TITLE
todo-list回车后生成的不是todolist格式

### ISSUE THREAD

**Issue by lvxi0605** [code-farmer-i/vue-markdown-editor#52]
![image](https://user-images.githubusercontent.com/19297660/100203564-bb7d6580-2f3d-11eb-9a72-6ffb4346e7ff.png)

**Comment by lvxi0605** [comment]
![image](https://user-images.githubusercontent.com/19297660/100203767-fc757a00-2f3d-11eb-9812-c889fb34dd8f.png)

**Comment by code-farmer-i** [comment]
这个是正常的
