### ISSUE TITLE
如何关闭预览时点击图片查看图片的功能，目前手机端是会有问题

### ISSUE THREAD

**Issue by lvxi0605** [code-farmer-i/vue-markdown-editor#53]
![image](https://user-images.githubusercontent.com/19297660/100208882-2c278080-2f44-11eb-8afa-a5a275522381.png)

**Comment by code-farmer-i** [comment]
![Uploading CF17B554-1B67-4D70-B7E3-ED85E6530627.png…]() 没问题啊

**Comment by code-farmer-i** [comment]
![403CD141-58C3-4C64-85E8-A4F0BDCC1D52](https://user-images.githubusercontent.com/15082905/100290997-96c5d400-2fb7-11eb-942b-ec54b3554eb1.png)

**Comment by lvxi0605** [comment]
![image](https://user-images.githubusercontent.com/19297660/100296388-05f6f480-2fc7-11eb-9e2d-454c68c3ea39.png)

**Comment by lvxi0605** [comment]
电脑端也不行，能不能点击图片不要预览

**Comment by lvxi0605** [comment]
https://www.lvxiblog.cn/blog/90 麻烦大佬看下为啥

**Comment by code-farmer-i** [comment]
你没引入样式

**Comment by code-farmer-i** [comment]
你是用的preview组件吗 ，要引入 import '@kangc/v-md-editor/lib/style/preview.css';

**Comment by lvxi0605** [comment]
好了，就是因为没引入这个 import '@kangc/v-md-editor/lib/style/preview.css'; ，好奇怪之前都是好的，可能我不小心删了这个行代码，然后浏览器缓存了这个文件

**Comment by lvxi0605** [comment]
谢谢大佬
