### ISSUE TITLE
Inline HTML tags not rendering in preview after webpack build

### ISSUE THREAD

**Issue by leehsueh** [code-farmer-i/vue-markdown-editor#55]
I'm observing a weird issue where inline HTML tags are not rendering correctly in the preview only after webpack has built the bundle. If I wrap content with inline HTML tags with block tags (e.g. a `<p>` or `<div>`) then that renders fine. However, if I'm just running the app locally using webpack dev server, it works as expected and I don't need to wrap with block level tags. See screenshots below:

### After webpack build
![image](https://user-images.githubusercontent.com/634864/100787328-53f56900-33c8-11eb-8175-f8405d9756af.png)

### Before webpack build
![image](https://user-images.githubusercontent.com/634864/100787610-bcdce100-33c8-11eb-85ab-a7b336b27607.png)

#### package.json
```
dependencies: {
  ...,
  "@kangc/v-md-editor": "^1.5.3",
  ...
}
```

#### register_vue_markdown_editor.js
```
import Vue from 'vue'

import VueMarkdownEditor from '@kangc/v-md-editor'
import enUS from '@kangc/v-md-editor/lib/lang/en-US'
import '@kangc/v-md-editor/lib/style/base-editor.css'
import githubTheme from '@kangc/v-md-editor/lib/theme/github.js'

VueMarkdownEditor.lang.use('en-US', enUS)
VueMarkdownEditor.use(githubTheme)
Vue.use(VueMarkdownEditor)
```

#### importing for .vue components 
```
<script>
import './register_vue_markdown_editor'

export default {
  name: 'ComponentName',
  ...
}
</script>
```

#### Explanation
I'm using separate webpack chunks for different parts of an app - one part is user-facing and the other is internal-facing for administrators. The markdown editor is only needed for administrators, so I don't want to include it in the user-facing chunk. Thus, I have the vue-markdown-editor registration in a separate js file, and I import that file in .vue components that require it. My thought is basically we only globally register vue-markdown-editor if at least one component requires it.

If there's something wrong with how I'm doing this, please let me know. Thanks for your hard work!

**Comment by code-farmer-i** [comment]
I can't reproduce the question
