### ISSUE TITLE
图片工具栏显示文章的图片详情

### ISSUE THREAD

**Issue by rieval** [code-farmer-i/vue-markdown-editor#57]
类似的功能：https://github.com/hinesboy/mavonEditor

我之前是使用上面那个项目的，后来因为升级到 Vue 3 后无法使用，看了下 issue 才找到大佬的项目

大概功能就是：

- 图片工具栏遍历文章中的图片，并根据图片的 desc 挨个显示出来
- 后面有一个 x 按钮，点击 x 按钮，会删除文章中对应的图片，然后触发一个回调事件（传递图片的 desc 和 src 参数）
- 上传图片后，如果返回图片的信息有长和高的信息，可以可选地添加图片的长和高

大佬有时间的话能否考虑一下实现这个功能呢 🙏

**Comment by code-farmer-i** [comment]
为了清理静态资源？

**Comment by rieval** [comment]
> 为了清理静态资源？

是的，毕竟上传到oss，这样就不用手动删除了😂

**Comment by code-farmer-i** [comment]
你可以自己实现0.0

**Comment by rieval** [comment]
> 你可以自己实现0.0

小白一个😂
