### ISSUE TITLE
iframe tag?

### ISSUE THREAD

**Issue by daep93** [code-farmer-i/vue-markdown-editor#64]
First of all, I really appreciate your awesome works. It is very helpful to me. 
However, I found that iframe tag not work when I was supposed to insert youtube embed.
How can i use iframe tag in your markdown editor?
![image](https://user-images.githubusercontent.com/63167589/107151313-3d115b00-69a5-11eb-817e-13b893135e12.png)

Best regards.

**Comment by code-farmer-i** [comment]
https://code-farmer-i.github.io/vue-markdown-editor/senior/xss-extend.html

**Comment by daep93** [comment]
ok, thank you! now, I understand xss-extend help me to use iframe tag. It works. Thank you !!!!!!!!!!!!!
```javascript
import VMdEditor from '@kangc/v-md-editor';

VMdEditor.xss.extend({
  // extend white list
  whiteList: {
    source: [],
    iframe:['src']
  },
});

```
