### ISSUE TITLE
Text always justified and line breaks in the middle of words

### ISSUE THREAD

**Issue by tom-richter** [code-farmer-i/vue-markdown-editor#65]
I read through the documentation, but couldn't find the settings where I can adjust the text alignment. Right now it is always justified, without respect to word endings. This makes the text kind of hard to read. How can I change the text alignment?

![Screenshot from 2021-02-07 21-32-38](https://user-images.githubusercontent.com/68494402/107158863-0b8c9580-698d-11eb-9e87-8d863f1f49ad.png)

**Comment by tom-richter** [comment]
Sorry, this is just a simple CSS thing with `word-break: normal;`

**Comment by LindezaGrey** [comment]
Hi, i am facing the same problem, where exactly did you cahnge the css?

**Comment by tom-richter** [comment]
I styled it this way:

```
.github-markdown-body,
.v-md-editor-preview,
.v-md-textarea-editor textarea {
  word-break: normal !important;
}
```

**Comment by LindezaGrey** [comment]
thank you, works for me!
