### ISSUE TITLE
vue3中 提示信息 -> 详情信息 出错

### ISSUE THREAD

**Issue by Lee-Jp** [code-farmer-i/vue-markdown-editor#67]
复现步骤：vue3使用进阶版，引入提示信息组件，选择插入详情信息会报错
报错信息如下【TypeError: Cannot read property 'defaultTitle' of undefined】

**Comment by code-farmer-i** [comment]
> 复现步骤：vue3使用进阶版，引入提示信息组件，选择插入详情信息会报错
> 报错信息如下【TypeError: Cannot read property 'defaultTitle' of undefined】

最新版吗？

**Comment by Lee-Jp** [comment]
对，用的npm上面下载的包

**Comment by code-farmer-i** [comment]
> 对，用的npm上面下载的包

看下具体版本号

**Comment by ahsan-a** [comment]
I got this on `@kangc/v-md-editor@1.6.0`. 

(Google Translate:) 我知道了 `@kangc/v-md-editor@1.6.0`.

**Comment by Lee-Jp** [comment]
抱歉我用package-lock.json锁定了2.2.0版本，升级2.2.1版本就解决了 - -
