### ISSUE TITLE
...

### ISSUE THREAD

**Issue by zengkaii** [code-farmer-i/vue-markdown-editor#68]
..

**Comment by code-farmer-i** [comment]
http://ckang1229.gitee.io/vue-markdown-editor/zh/quick-start.html#%E5%AE%89%E8%A3%85%E6%94%AF%E6%8C%81-vue3-%E7%9A%84%E7%89%88%E6%9C%AC

**Comment by code-farmer-i** [comment]
npm install @kangc/v-md-editor@next

**Comment by zengkaii** [comment]
> npm install @kangc/v-md-editor@next

thanks

**Comment by zengkaii** [comment]
> http://ckang1229.gitee.io/vue-markdown-editor/zh/quick-start.html#%E5%AE%89%E8%A3%85%E6%94%AF%E6%8C%81-vue3-%E7%9A%84%E7%89%88%E6%9C%AC

my falult
