### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by steel-li** [code-farmer-i/vue-markdown-editor#7]
* 1、编辑器现在看到的效果是全屏时 **半编辑变预览**，**无 可全部预览（只显示预览页）**，**无 可全部编辑（只显示编辑页）**，虽然是可以通过`mode`去动态控制，对体验来说还是有些问题
* 2、提示信息：提示信息中会存在这个**提示、警告、注意**的字体，希望能去掉
![image](https://user-images.githubusercontent.com/48340400/81491375-89b5f180-92c0-11ea-950b-b789d8cdd957.png)
* 3、**上传图片后无法点击图片单独预览，要是图片截屏大的情况下，那么就无法具体查看图片内容（重点）**

**Comment by code-farmer-i** [comment]
问题1、3在 1.2.13版本解决，问题2可以自定义样式实现
