### ISSUE TITLE
vite vue3 项目中 引入组件报错 

### ISSUE THREAD

**Issue by wangchaoxx** [code-farmer-i/vue-markdown-editor#71]
<img width="769" alt="Snipaste_2021-04-04_17-20-26" src="https://user-images.githubusercontent.com/42869522/113504464-ce96e680-956a-11eb-861b-920df8e9b557.png">

**Comment by code-farmer-i** [comment]
贴下代码

**Comment by wangchaoxx** [comment]
重现不了了，我刚试了一下，可以用了

**Comment by code-farmer-i** [comment]
行吧0 0
