### ISSUE TITLE
How i can implement this with nuxt

### ISSUE THREAD

**Issue by silvesterwali** [code-farmer-i/vue-markdown-editor#72]
hi i have read the doc and this is amazing .but don't see how to implement this with nuxt . thank for replay

**Comment by code-farmer-i** [comment]
![image](https://user-images.githubusercontent.com/15082905/113667670-b26a8500-96e3-11eb-8032-633b0edb272d.png)

plugins/v-md-editor.js

![image](https://user-images.githubusercontent.com/15082905/113667837-ee054f00-96e3-11eb-8a04-e59dcd9589e4.png)

nuxt.config.js
![image](https://user-images.githubusercontent.com/15082905/113667604-9c5cc480-96e3-11eb-8207-a30e9524f700.png)

**Comment by silvesterwali** [comment]
ok thanks ...i will try this one ...

**Comment by silvesterwali** [comment]
this is work
