### ISSUE TITLE
强烈建议样式组件封装好，不要被外界所干扰

### ISSUE THREAD

**Issue by ashuicoder** [code-farmer-i/vue-markdown-editor#76]
像使用了normalize.css这种，显示效果全部乱了

**Comment by code-farmer-i** [comment]
具体是什么样式呢 ul ol？

**Comment by code-farmer-i** [comment]
具体是什么样式呢 ul ol？

**Comment by ashuicoder** [comment]
> 具体是什么样式呢 ul ol？

不仅仅只是ul、ol，字体大小、行高、间距等都受到影响，意思是公用组件不应该去约束用户怎么定义网站的样式吧，还有希望加个小功能，上传的图片默认居中。。。

**Comment by code-farmer-i** [comment]
新版本样式优化了。上传的图片默认居中你可以在上传图片成功后调用编辑器的insert方法自己实现。
```js
editor.insert(() => {
  return {
    text: `<div style="text-align: center"><img src=""/></div>`,
  };
});
```

**Comment by AShuiCoder** [comment]
![image](https://user-images.githubusercontent.com/47807522/116655353-8a5a0300-a9bd-11eb-88dc-0a1730c43ad4.png)

**Comment by ashuicoder** [comment]
> 新版本样式优化了。上传的图片默认居中你可以在上传图片成功后调用编辑器的insert方法自己实现。
> 
> ```js
> editor.insert(() => {
>   return {
>     text: `<div style="text-align: center"><img src=""/></div>`,
>   };
> });
> ```

好的，感谢

**Comment by ashuicoder** [comment]
> > 新版本样式优化了。上传的图片默认居中你可以在上传图片成功后调用编辑器的insert方法自己实现。
> > ```js
> > editor.insert(() => {
> >   return {
> >     text: `<div style="text-align: center"><img src=""/></div>`,
> >   };
> > });
> > ```
> 
> 好的，感谢

ul，ol的上下边距加一下
![image](https://user-images.githubusercontent.com/47807522/116655711-21bf5600-a9be-11eb-9616-20706105908f.png)

**Comment by code-farmer-i** [comment]
好的 下个版本加上
