### ISSUE TITLE
在 vue3 中使用报错的问题。

### ISSUE THREAD

**Issue by code-farmer-i** [code-farmer-i/vue-markdown-editor#86]
请确认安装的版本是否为支持vue3的版本。

安装支持 vue3 的版本：

```bash
# 使用 npm
npm i @kangc/v-md-editor@next -S

# 使用yarn
yarn add @kangc/v-md-editor@next
```

**Comment by zengbotao** [comment]
生产环境可以正常运行，但使用vite打包时，报错，无法编译：

vite v3.2.4 building for production...
✓ 1603 modules transformed.
'default' is not exported by node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by node_modules/@kangc/v-md-editor/lib/base-editor.js
file: D:/Example/vite_ts_vue3/node_modules/@kangc/v-md-editor/lib/base-editor.js:1:7
1: (function webpackUniversalModuleDefinition(root, factory) {
          ^
2:   if(typeof exports === 'object' && typeof module === 'object')
3:     module.exports = factory(require("vue"));
error during build:

**Comment by ChrisNi888** [comment]
> 生产环境可以正常运行，但使用vite打包时，报错，无法编译：
> 
> vite v3.2.4 building for production... ✓ 1603 modules transformed. 'default' is not exported by node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by node_modules/@kangc/v-md-editor/lib/base-editor.js file: D:/Example/vite_ts_vue3/node_modules/@kangc/v-md-editor/lib/base-editor.js:1:7 1: (function webpackUniversalModuleDefinition(root, factory) { ^ 2: if(typeof exports === 'object' && typeof module === 'object') 3: module.exports = factory(require("vue")); error during build:

请问这个问题后来解决了吗，我也遇到同样的问题了

error during build:
RollupError: node_modules/.pnpm/@kangc+v-md-editor@2.3.18_@vue+compiler-sfc@3.4.27_vue@3.4.27_typescript@5.3.3_/node_modules/@kangc/v-md-editor/lib/base-editor.js (4:7): "default" is not exported by "vue?commonjs-external", imported by "node_modules/.pnpm/@kangc+v-md-editor@2.3.18_@vue+compiler-sfc@3.4.27_vue@3.4.27_typescript@5.3.3_/node_modules/@kangc/v-md-editor/lib/base-editor.js".
file: E:/L1/CS/Vue/VueProjects/vue_admin_usefastapi3/node_modules/.pnpm/@kangc+v-md-editor@2.3.18_@vue+compiler-sfc@3.4.27_vue@3.4.27_typescript@5.3.3_/node_modules/@kangc/v-md-editor/lib/base-editor.js:4:7
