### ISSUE TITLE
Vite 中关于 VuePress + PrismJS 无法高亮其他语言的问题

### ISSUE THREAD

**Issue by rieval** [code-farmer-i/vue-markdown-editor#94]
这是一个 Demo：
[代码](https://codesandbox.io/s/musing-firefly-hw1p8)
[预览](https://hw1p8.sse.codesandbox.io/)

我发现只有 `JavaScript` 语言能高亮，其他语言，类似 `JSON` 和 `Bash` 这些好像都不能高亮，我是按照[教程](https://code-farmer-i.github.io/vue-markdown-editor/zh/theme/vuepress.html#%E6%89%A9%E5%B1%95%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE%E8%AF%AD%E8%A8%80%E5%8C%85)中的方式安装 `babel-plugin-prismjs` 和 `rollup-plugin-babel` 这两个插件的

初步断定可能是 Vite 无法识别这个 `babel` 插件的问题，因为我发现不论是否在 `vite.config.ts` 里引入 `babel` 插件，所打包的文件大小并不会改变。

**Comment by code-farmer-i** [comment]
已解决 换成 vite-plugin-prismjs 参考文档 [vite 中扩展代码高亮语言包](http://ckang1229.gitee.io/vue-markdown-editor/zh/theme/vuepress.html#vite-%E4%B8%AD%E6%89%A9%E5%B1%95%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE%E8%AF%AD%E8%A8%80%E5%8C%85)
